import { randomUUID } from 'crypto';
import Participant from '../models/Participant.js';
import { progressMap } from './progress.service.js';

export const mapRowsForInsert = (rows, fileType) => rows.map((row) => ({ _id: randomUUID(), email: row.email, employeeId: row.employeeId, role: row.role, site: row.site, firstName: row.firstName, lastName: row.lastName, rawData: { fileType } }));
export async function findExistingEmails(emails) { const normalized = Array.from(new Set((emails || []).filter(Boolean))); if (!normalized.length) return []; return (await Participant.find({ email: { $in: normalized } }).select('email').lean()).map((r) => r.email); }
export async function findExistingEmployeeIds(employeeIds) { const normalized = Array.from(new Set((employeeIds || []).filter(Boolean))); if (!normalized.length) return []; return (await Participant.find({ employeeId: { $in: normalized } }).select('employeeId').lean()).map((r) => r.employeeId).filter(Boolean); }
export function buildRowsWithoutDuplicates(rows, existingDuplicateEmails, existingDuplicateEmployeeIds) { const e = new Set(existingDuplicateEmails); const x = new Set(existingDuplicateEmployeeIds); const seenE = new Set(); const seenX = new Set(); return rows.filter((r) => { if (e.has(r.email) || (r.employeeId && x.has(r.employeeId)) || seenE.has(r.email) || (r.employeeId && seenX.has(r.employeeId))) return false; seenE.add(r.email); if (r.employeeId) seenX.add(r.employeeId); return true; }); }
export async function processUpload(uploadId, insertRows) { let progress = progressMap.get(uploadId); if (!progress) return; progress.status = 'processing'; progress.total = insertRows.length; let insertedTotal = 0; for (let i = 0; i < insertRows.length; i += 1000) { progress = progressMap.get(uploadId); if (!progress || progress.status === 'canceling' || progress.status === 'canceled') return; const chunk = insertRows.slice(i, i + 1000); await Participant.insertMany(chunk, { ordered: false }).then((r) => { insertedTotal += r.length; }).catch((e) => { insertedTotal += e?.insertedDocs?.length || 0; }); progress.processed = Math.min(insertRows.length, i + chunk.length); progress.inserted = insertedTotal; } progress.status = 'done'; progressMap.set(uploadId, progress); }
